### ISSUE TITLE
 Cannot find module 'path-is-absolute' with version 5.2.0

### ISSUE THREAD

**Issue by stevewillard** [babel/babel-loader#80]
Anyone else getting this error?

```
/Users/swillard/Documents/github/platform-js/node_modules/webpack/node_modules/webpack-core/lib/NormalModuleMixin.js:206
					throw e;
					      ^
Error: Cannot find module 'path-is-absolute'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/swillard/Documents/github/platform-js/node_modules/babel-loader/lib/resolve-rc.js:17:18)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/swillard/Documents/github/platform-js/node_modules/babel-loader/index.js:7:17)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
```

**Comment by jakemhiller** [comment]
Yes, i'm also getting this error.

**Comment by Stuk** [comment]
Same, introduced by https://github.com/babel/babel-loader/commit/bedc8c5da6645a27a6d4c16fad8e1bb3dd91d8fe

**Comment by mstuart** [comment]
me2

**Comment by gfranko** [comment]
Also seeing this issue

**Comment by stanleyhlng** [comment]
Yes. saw that too.

**Comment by globexdesigns** [comment]
+1

**Comment by hshansen7** [comment]
same.

**Comment by thejameskyle** [comment]
ping @Couto @sebmck

**Comment by Couto** [comment]
I'm on it

**Comment by stanleyhlng** [comment]
thanks!

**Comment by Couto** [comment]
Actually the module is not needed at all, it was my mistake since I removed from the package.json but forgot to remove from node_modules

**Comment by Couto** [comment]
Ok... You can find the fix on the 5.2.1 version on npm

**Comment by mdmasumbillah** [comment]
Me too. Faced this error And solve this
code: npm i
